services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G # Limitamos el uso para que no colapse el sistema

