services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /home/ubuntu/n8n-project/ollama_data:/root/.ollama
      - /home/usuario/proyecto/infra/init-ollama.sh:/init-ollama.sh

    # Usamos formato de lista para evitar errores de parseo
    entrypoint: ["/bin/bash", "-c", "/bin/ollama serve & pid=$!; sleep 5; echo 'Descargando modelo...'; /bin/ollama pull llama3.1; wait $pid"]

    restart: always
    deploy:
      resources:
        limits:
          memory: 8G # Limitamos el uso para que no colapse el sistema

