services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      # Usa rutas consistentes en tu servidor Ubuntu
      - /home/ubuntu/n8n-project/ollama_data:/root/.ollama
      - /home/ubuntu/n8n-project/infra/init-ollama.sh:/init-ollama.sh

    # Usamos formato de lista para evitar errores de parseo
    entrypoint: ["/bin/bash", "/init-ollama.sh"]
    
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G # Limitamos el uso para que no colapse el sistema

