name: Deploy a OCI

on:
  push:
    branches: [ main ]

jobs:
  deploy-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy files to Server A
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_A }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/home/ubuntu/n8n-project/"

      - name: Deploy n8n Servidor A
        uses: appleboy/ssh-action@master
        env:
          
          OLLAMA_URL: ${{ secrets.OLLAMA_URL }}
        with:
          host: ${{ secrets.SSH_HOST_A }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/n8n-project/

            export OLLAMA_URL=$OLLAMA_URL
            docker compose -f infra/docker-compose.server-n8n.yml down
            docker compose -f infra/docker-compose.server-n8n.yml pull
            docker compose -f infra/docker-compose.server-n8n.yml up -d

  deploy-b:
    runs-on: ubuntu-latest
    needs: deploy-a
    steps:
      - uses: actions/checkout@v4

      - name: Copy files to Server B
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_B }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          proxy_host: ${{ secrets.SSH_HOST_A }}
          proxy_username: ${{ secrets.SSH_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/home/ubuntu/n8n-project/" # Usamos la misma ruta para evitar confusiones

      - name: Deploy Ollama Servidor B
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_B }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          proxy_host: ${{ secrets.SSH_HOST_A }}
          proxy_username: ${{ secrets.SSH_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/n8n-project/

            # Dar permiso de ejecución al script antes de levantar el contenedor
            chmod +x infra/init-ollama.sh

            mkdir -p ollama_data
            
            # Usamos rutas relativas desde la raíz del proyecto para mayor limpieza
            docker compose -f infra/docker-compose.server-ollama.yml down
            docker compose -f infra/docker-compose.server-ollama.yml pull
            docker compose -f infra/docker-compose.server-ollama.yml up -d